apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularfinal
  labels:
    app: angularfinal
spec:
  replicas: REPLICA
  selector:
    matchLabels:
      app: angularfinal
  template:
    metadata:
      labels:
        app: angularfinal
    spec:
      containers:
      - name: angular
        image: DOCKER_IMAGE:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API
          valueFrom:
            configMapKeyRef:
              name: angular-config
              key: API
